### ISSUE TITLE
Pass in a private key?

### ISSUE THREAD

**Issue by Jared-Dahlke** [pointnetwork/granax#1]
Hello, 
how would I pass in a private key?

Something like this?
```
tor.on('ready', function() {
  tor.createHiddenService('127.0.0.1:8080', {privateKey: 'adfafadfafa...'}, (err, result) => {
    console.info(`Service URL: ${result.serviceId}.onion`);
    console.info(`Private Key: ${result.privateKey}`);
  });
});
```

**Comment by tankakatan** [comment]
Hi @JaredDahlke, thank you very much for the issue. Currently we are working on improvement of the key management process.
However I've noticed that you are using `tor` hidden service in your example. Could you please elaborate on the use case you are trying to cover? I believe it will help us to provide a better solution.

**Comment by Jared-Dahlke** [comment]
Hi I am trying to always generate the same onion url!

**Comment by Jared-Dahlke** [comment]
Hi I am trying to always generate the same onion url

**Comment by sergevar** [comment]
Hi Jared, this repository, and several others, are forks of repositories from a GitLab user named Emery Rose aka @DeadCanaries. We used to use their package "kadence" to have a Javascript-based implementation of S/Kademlia DHT, for which "granax" is one of dependencies.

In May 2021, Emery completely vanished from the internet, all accounts wiped out. To continue using the package, we had to host it ourselves on github, as well as all the dependencies. It does not mean we know them in and out and can provide proper support for them. In fact, the packages might be severely outdated by now because they are frozen and not being maintained.

At this moment, our whole engineering team is working hard to meet deadlines on our implementation of a completely decentralized web 3.0 internet called Point Network. Because of a combination of these reasons, we cannot provide continuous maintenance and support for these packages.

You could try reaching out to OriginTrail team who did the same, archiving these repositories in parallel with us. Perhaps, unlike us, they are still using kadence and granax, and can help you. https://github.com/OriginTrail/granax

**Comment by Jared-Dahlke** [comment]
What the hell is Web3? Just focus on bitcoin if you want o be successful

**Comment by sergevar** [comment]
Horse maximalists in the house? :) "What the hell is a car"

**Comment by Jared-Dahlke** [comment]
😂 bitcoin is the car

**Comment by sergevar** [comment]
Nothing against cars or horses, everything against maximalists saying it's the final form, discouraging others from making planes and choppers and spaceships

**Comment by Jared-Dahlke** [comment]
Do you guys have a token?

**Comment by sergevar** [comment]
Not yet - building the framework itself now - decentralized domains, storage, email, twitter... Will only launch when the product is finished

**Comment by Jared-Dahlke** [comment]
Very interesting. Does the token exist to satisfy a technical requirement ?

**Comment by sergevar** [comment]
Yes. Part of it goes to validators for transaction fees, part of it converted for decentralized storage payments etc.

But not just for technical reasons. The legacy internet didn't have a built-in payment system, and it led to a hodgepodge of Visa/Mastercard/Paypal/Webmoney/etc. The new internet has to have a default currency. Even though Point Wallet would support several chains (including Bitcoin and LN), if Point Network becomes the de-facto standard of web3, it would be convenient for all financial functions to be denominated in POINT by default.

But this is slightly off-topic, I suggest you check out our whitepaper at https://pointnetwork.io/link/whitepaper or chat with us at https://t.me/pointnetworkchat if you're really curious. And I do hope you find help with your granax setup.
